---
version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - "/"
      - "/automations"
      - "/component-changes"
      - "/components"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
