name: Create component changes list
runs:
  using: composite
  steps:
    - name: Check out release branch from GitHub
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        repository: esphome/esphome
        ref: release
        fetch-depth: 500
        path: esphome
    - name: Find changed components
      shell: bash
      run: |
        mkdir output
        ./component-changes/get-changes.sh esphome > output/changed_components.json
    - name: Validate schema
      uses: cardinalby/schema-validator-action@77eb17b070f282db4680215551cae4d9c379f2f4  # v3
      with:
        file: output/changed_components.json
        schema: component-changes/schema.json
    - name: Copy schema to output
      shell: bash
      run: cp component-changes/schema.json output/changed_components.schema.json
    - name: Upload artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
      with:
        name: component-changes
        path: output
