name: Create component changes list
runs:
  using: composite
  steps:
    - name: Check out release branch from GitHub
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        repository: esphome/esphome
        ref: release
        fetch-depth: 500
        path: esphome
    - name: Find changed components
      shell: bash
      run: |
        mkdir output
        ./component-changes/get-changes.sh esphome > output/changed_components.json
    - name: Validate schema
      uses: cardinalby/schema-validator-action@95ce895b6846cc7d931785fcaa46c84816753612  # v3.1.2
      with:
        file: output/changed_components.json
        schema: component-changes/schema.json
    - name: Copy schema to output
      shell: bash
      run: cp component-changes/schema.json output/changed_components.schema.json
    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: component-changes
        path: output
