name: Build automations.json
inputs:
  version:
    description: The version of ESPHome to generate automations for.
    required: true
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.10'
    - name: Set up UV
      uses: astral-sh/setup-uv@v6.1.0
    - name: Check out ESPHome from GitHub
      uses: actions/checkout@v4.2.2
      with:
        repository: esphome/esphome
        ref: ${{ inputs.version }}
        path: esphome
    - name: Set up ESPHome
      shell: bash
      working-directory: esphome
      run: script/setup
    - name: Build automations.json
      shell: bash
      run: |
        source esphome/venv/bin/activate
        mkdir output/${{ inputs.version }}
        ./automations/get-automations.sh esphome > output/${{ inputs.version }}/automations.json
    - name: Validate schema
      uses: cardinalby/schema-validator-action@3.1.1
      with:
        file: output/${{ inputs.version }}/automations.json
        schema: automations/schema.json
    - name: Copy schema to output
      shell: bash
      if: ${{ inputs.version == 'dev' }}
      run: cp automations/schema.json output/automations.schema.json
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: automations-${{ inputs.version }}
        path: output
